inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

AllCops:
  Exclude: 
    - db/schema.rb
    - db/migrate/*.rb
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
